[package]
name = "zbl_py"
version.workspace = true
edition = "2021"

[lib]
name = "zbl"
crate-type = ["cdylib"]

[dependencies]
zbl = { path = "../zbl" }
thiserror = "1"

[dependencies.pyo3]
version = "0.20"
features = ["extension-module"]
