[package]
name = "zbl_py"
version = "0.1.1"
edition = "2021"

[lib]
name = "zbl"
crate-type = ["cdylib"]

[dependencies]
zbl = { path = "../zbl" }
thiserror = "1"

[dependencies.pyo3]
version = "0.19"
features = ["extension-module"]
